### ISSUE TITLE
我是来夸人滴

### ISSUE THREAD

**Issue by ruicky** [CaoMeiYouRen/push-all-in-one#13]
还是你厉害了，我之前就在待办事项中要写一个node包，来实现全部统一推送。结果刚刚看到你这个。
![image](https://user-images.githubusercontent.com/6834731/117404641-e0d6bc80-af3c-11eb-8d2a-1c875c096f4a.png)

**Comment by ruicky** [comment]
> 还是你厉害了，我之前就在待办事项中要写一个node包，来实现全部统一推送。结果刚刚看到你这个。
> ![image](https://user-images.githubusercontent.com/6834731/117404641-e0d6bc80-af3c-11eb-8d2a-1c875c096f4a.png)

还没开始，就已经结束了...

**Comment by CaoMeiYouRen** [comment]
哈哈，谢谢。实际上我也只是简单整合了下，没什么太大难度。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月7日(星期五) 下午2:05
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [CaoMeiYouRen/push-all-in-one] 我是来夸人滴 (#13)

**Comment by CaoMeiYouRen** [comment]
我看了下你的开发要求，其实比我的实现要完善一些，可以考虑自己再实现一下
